config/routes.rb
YourNameApp::Application.routes.draw do

  resources :students
  root :to => 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :address, :fullname, :graduated_from, :place_date_birth, :year_graduated

  validates :fullname, :presence => true
  validates :place_date_birth, :presence => true
  validates :address, :presence => true
  validates :graduated_from, :presence => true
  validates :year_graduated, :presence => true, :numericality => { :greater_than => 2000, :less_than_or_equal_to => Date.today.year }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
    if !@students
  		render :text => "No Student Enrolled yet"
  	end
  end

  def new
  	@student = Student.new
  end
  def create
  	@student = Student.new(params[:student])
  	if @student.save
  		redirect_to(students_path)
  	else
			render "new"
  	end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end
  def update
    @student = Student.find(params[:id])
  	if @student.update_attributes(params[:student])
  		render "show"
  	else
  		render "edit"
  	end
  end

  def destroy
  	@student = Student.find(params[:id])
  	if @student.destroy
  		redirect_to(students_path)
  	else
  		render "show"
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YourNameApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1>Edit Data Student</h1>

<%= link_to "Back To List Student", students_path %><br/>

<%= form_for(@student) do |f| %>
  <%= f.label :fullname, "Full Name"%><%= raw @student.errors[:fullname].first %><br/>
  <%= f.text_field :fullname, :size => "50"%><br/>
  <%= f.label :place_date_birth, "Place, Date Birth"%><%= raw @student.errors[:place_date_birth].first %><br/>
  <%= f.text_field :place_date_birth, :size => "50"%><br/>
  <%= f.label :address, "Address now" %><%= raw @student.errors[:address].first %><br/>
  <%= f.text_area :address, :size => "70x20" %><br/>
  <%= f.label :graduated_from, "Graduated From"%><%= raw @student.errors[:graduated_from].first %><br/>
  <%= f.text_field :graduated_from, :size => "50"%><br/>
  <%= f.label :year_graduated, "Year Graduated"%><%= raw @student.errors[:year_graduated].first %><br/>
  <%= f.text_field :year_graduated, :size => "20"%><br/>
  <%= f.submit :Enroll %>
<% end %>

app/views/students/index.html.erb
<h1>List Student Enrolled</h1>

<%= link_to "Enrol Student", new_student_path %><br/>

<% @students.each do |student| %>
<p><%= link_to student.fullname, student_path(student.id) %>&nbsp;<%= student.address %></p>
<% end %>

app/views/students/new.html.erb
<h1>Student Form Registration</h1>

<%= link_to "Back To List Student", students_path %><br/>

<%= form_for(@student) do |f| %>
  <%= f.label :fullname, "Full Name"%><%= raw @student.errors[:fullname].first %><br/>
  <%= f.text_field :fullname, :size => "50"%><br/>
  <%= f.label :place_date_birth, "Place, Date Birth"%><%= raw @student.errors[:place_date_birth].first %><br/>
  <%= f.text_field :place_date_birth, :size => "50"%><br/>
  <%= f.label :address, "Address now" %><%= raw @student.errors[:address].first %><br/>
  <%= f.text_area :address, :size => "70x20" %><br/>
  <%= f.label :graduated_from, "Graduated From"%><%= raw @student.errors[:graduated_from].first %><br/>
  <%= f.text_field :graduated_from, :size => "50"%><br/>
  <%= f.label :year_graduated, "Year Graduated"%><%= raw @student.errors[:year_graduated].first %><br/>
  <%= f.text_field :year_graduated, :size => "20"%><br/>
  <%= f.submit :Enroll %>
<% end %>

app/views/students/show.html.erb
<h1>Detail Student</h1>

<%= link_to "Back To List Student", students_path %><br/>

<p>Full Name : <%= @student.fullname %></p>
<p>Place & Date Birth : <%= @student.place_date_birth %></p>
<p>Address Now : <%= @student.address %></p>
<p>Graduated From : <%= @student.graduated_from %></p>
<p>Year Graduated : <%= @student.year_graduated %></p>
<%= link_to "EDIT", edit_student_path(@student.id) %>&nbsp;|&nbsp;
<%= link_to "DELETE", @student, method: :delete, data: {confirm: "MDwikuntobayu, Are you sure? "}  %>